services:
  db:
    image: "mysql"
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "supersecretpassword"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - "db_data:/var/lib/mysql"
  app:
    depends_on:
      - db
    image: "mcdclink:local"
    environment:
      SPRING_DATASOURCE_USERNAME: "${DB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/${DB_NAME}?useSSL=false"
    ports:
      - "8888:8888"
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      sleep 10
      java -cp @/app/jib-classpath-file @/app/jib-main-class-file
      "
volumes:
  db_data:
