# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - 'main'

env:
  docker-repo: "ghcr.io/jakubaakk/mc-dc-link-ws"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Setup JDK 17'
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Run tests
#        run: ./gradlew test


      - name: Get version
        id: get-version
        run: echo "::set-output name=VERSION::$(./gradlew -q currentVersion)"

      - name: Git tag
        run: |
          git tag v${{steps.get-version.outputs.VERSION}}
          git push origin v${{steps.get-version.outputs.VERSION}}

      - name: Build Docker image
        run: ./gradlew jib --image="${{env.docker-repo}}:${{steps.get-version.outputs.VERSION}}"

      - name: Build jar
        run: ./gradlew bootJar

      - name: Create Github release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{steps.get-version.outputs.VERSION}}
          release_name: Release v${{steps.get-version.outputs.VERSION}}
          draft: true
          prerelease: false

      - name: Upload jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/mc-dc-link-ws-${{steps.get-version.outputs.VERSION}}.jar
          asset_name: mc-dc-link-ws-${{steps.get-version.outputs.VERSION}}.jar
          asset_content_type: application/java-archive
